# Generated by Django 5.2.1 on 2025-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jpgupload',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='jpgupload',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdf/'),
        ),
        migrations.AlterField(
            model_name='jpgupload',
            name='jpeg_file',
            field=models.FileField(upload_to='uploads/jpg/'),
        ),
    ]
