# Generated by Django 5.2.1 on 2025-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_jpgupload_options_jpgupload_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpgupload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jpgupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTING', 'Converting to PDF'), ('SENDING', 'Sending Email'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='jpgupload',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
