# Generated by Django 5.2.1 on 2025-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_jpgupload_error_message_jpgupload_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jpeg_file', models.FileField(upload_to='uploads/jpg/')),
                ('_pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/pdf/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTING', 'Converting to PDF'), ('SENDING', 'Sending Email'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='JPGUpload',
        ),
    ]
